/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.paoe.view.panel;

import co.edu.usbbog.paoe.controller.logic.AsesoriaBusiness;
import co.edu.usbbog.paoe.controller.logic.PacienteBusiness;
import co.edu.usbbog.paoe.model.Paciente;
import co.edu.usbbog.paoe.view.frame.Principal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Nicolas
 */
public class AsesoriaJPanel extends javax.swing.JPanel {

    private Principal principal;
    private IniciarSesionJPanel inicio;
    private AsesoriaBusiness asesoriaB;
    private final PacienteBusiness pacienteB;

    /**
     * Creates new form Presentacion
     */
    public AsesoriaJPanel(Principal principal) {

        this.principal = principal;
        initComponents();
        TextPrompt observaciones = new TextPrompt("Escriba acá las observaciones del paciente", this.jTextFieldObservaciones);
        this.inicio = new IniciarSesionJPanel(principal);
        this.nombreUsuario.setText(inicio.darNombreUsuario());
        this.asesoriaB = new AsesoriaBusiness();
        this.pacienteB = new PacienteBusiness();
    }

    private void irRegistrarJPanel() {
        principal.irRegistrarJPanel(this);
    }

    private void irAsesoriaJPanel() {
        principal.irAsesoriaJPanel(this);
    }

    private void irHistorialJPanel() {
        principal.irHistorialJPanel(this);
    }

    private void irIniciarSesionJPanel() {
        principal.irIniciarSesionJPanel(this);
    }

    private void irRegistrarPsicologoJPanel() {
        principal.irRegistrarPsicologoJPanel(this);
    }

    private Date ObtenerFecha() {
        Date fecha = null;
        try {
            Date now = new Date(System.currentTimeMillis());
            SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy-HH:mm:ss");
            SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
            String cadena = date.format(now) + " " + hour.format(now);
            fecha = date.parse(cadena);
        } catch (ParseException ex) {
            Logger.getLogger(AsesoriaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return fecha;
    }

    public void limpiar() {
        jTextFieldNumAsesoria.setText("");
        jTextFieldTipAcomp.setText("");
        jTextFieldAcceso.setText("");
        jTextFieldRemitidoPor.setText("");
        jTextFieldProblema.setText("");
        jTextFieldAcciones.setText("");
        jTextFieldAsistencia.setText("");
        jTextFieldCulminacion.setText("");
        jTextFieldRemitidoA.setText("");
        jTextFieldObservaciones.setText("");
    }

    private Paciente buscarPaciente() {
        Paciente p = pacienteB.findPaciente(Integer.parseInt(jTextFieldBuscar.getText()));
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nombreUsuario = new javax.swing.JLabel();
        boton1 = new co.edu.usbbog.paoe.view.image.Boton();
        boton2 = new co.edu.usbbog.paoe.view.image.Boton();
        boton3 = new co.edu.usbbog.paoe.view.image.Boton();
        boton4 = new co.edu.usbbog.paoe.view.image.Boton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        guardarAsesoria = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNumAsesoria = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTipAcomp = new javax.swing.JTextField();
        jTextFieldAcceso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldRemitidoPor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldProblema = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldAcciones = new javax.swing.JTextField();
        jTextFieldAsistencia = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldCulminacion = new javax.swing.JTextField();
        jTextFieldRemitidoA = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelNomPaciente = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelFinan = new javax.swing.JLabel();
        jLabelSemestre = new javax.swing.JLabel();
        jLabelCodigo1 = new javax.swing.JLabel();
        jLabelEdad1 = new javax.swing.JLabel();
        jLabelFinan1 = new javax.swing.JLabel();
        jLabelSemestre1 = new javax.swing.JLabel();
        jLabelNomPaciente1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldObservaciones = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nunito", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APPAOE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/emociones.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/river.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 1580, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        nombreUsuario.setFont(new java.awt.Font("Nunito", 1, 15)); // NOI18N
        nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuario.setText("Psicólogo");

        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/psicologo.png"))); // NOI18N
        boton1.setText("Registrar Psicólogo");
        boton1.setColorHover(new java.awt.Color(204, 204, 204));
        boton1.setColorNormal(new java.awt.Color(214, 217, 223));
        boton1.setColorPressed(new java.awt.Color(153, 153, 153));
        boton1.setColorTextHover(new java.awt.Color(0, 0, 0));
        boton1.setColorTextNormal(new java.awt.Color(0, 0, 0));
        boton1.setColorTextPressed(new java.awt.Color(0, 0, 0));
        boton1.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/emocion.png"))); // NOI18N
        boton2.setText("Asesoría");
        boton2.setColorHover(new java.awt.Color(204, 204, 204));
        boton2.setColorNormal(new java.awt.Color(214, 217, 223));
        boton2.setColorPressed(new java.awt.Color(153, 153, 153));
        boton2.setColorTextHover(new java.awt.Color(0, 0, 0));
        boton2.setColorTextNormal(new java.awt.Color(0, 0, 0));
        boton2.setColorTextPressed(new java.awt.Color(0, 0, 0));
        boton2.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/dosier.png"))); // NOI18N
        boton3.setText("Historial");
        boton3.setColorHover(new java.awt.Color(204, 204, 204));
        boton3.setColorNormal(new java.awt.Color(214, 217, 223));
        boton3.setColorPressed(new java.awt.Color(153, 153, 153));
        boton3.setColorTextHover(new java.awt.Color(0, 0, 0));
        boton3.setColorTextNormal(new java.awt.Color(0, 0, 0));
        boton3.setColorTextPressed(new java.awt.Color(0, 0, 0));
        boton3.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/nota.png"))); // NOI18N
        boton4.setText("Registrar Paciente");
        boton4.setColorHover(new java.awt.Color(204, 204, 204));
        boton4.setColorNormal(new java.awt.Color(214, 217, 223));
        boton4.setColorPressed(new java.awt.Color(153, 153, 153));
        boton4.setColorTextHover(new java.awt.Color(0, 0, 0));
        boton4.setColorTextNormal(new java.awt.Color(0, 0, 0));
        boton4.setColorTextPressed(new java.awt.Color(0, 0, 0));
        boton4.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/apagar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(nombreUsuario)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 230, 780));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/anadir.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 40, 30));

        guardarAsesoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/salvar.png"))); // NOI18N
        guardarAsesoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAsesoriaActionPerformed(evt);
            }
        });
        jPanel1.add(guardarAsesoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 40, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/buscar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 40, 30));

        jTextFieldBuscar.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 170, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jLabel8.setText("Número de Asesoría");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jTextFieldNumAsesoria.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jPanel4.add(jTextFieldNumAsesoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 237, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabel11.setText("Asesoría del Paciente");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 12, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jLabel10.setText("Tipo de Acompañamiento");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jTextFieldTipAcomp.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jPanel4.add(jTextFieldTipAcomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 237, -1));

        jTextFieldAcceso.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jPanel4.add(jTextFieldAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 237, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jLabel12.setText("Acceso al Servicio");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jTextFieldRemitidoPor.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jPanel4.add(jTextFieldRemitidoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 237, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jLabel13.setText("Remitido por");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jLabel14.setText("Problemática referenciada/trabajada");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jTextFieldProblema.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jPanel4.add(jTextFieldProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 237, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jLabel23.setText("Acciones realizadas");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jTextFieldAcciones.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jPanel4.add(jTextFieldAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 237, -1));

        jTextFieldAsistencia.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jPanel4.add(jTextFieldAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 237, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jLabel24.setText("Asistencia");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jLabel25.setText("Culminación");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jTextFieldCulminacion.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jPanel4.add(jTextFieldCulminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 237, -1));

        jTextFieldRemitidoA.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jPanel4.add(jTextFieldRemitidoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 237, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jLabel26.setText("Remitido a");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 590, 510));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabelNomPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNomPaciente.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabelNomPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabel29.setText("Información del Paciente");

        jLabelCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabelCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabelEdad.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabelEdad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabelFinan.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFinan.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabelFinan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabelSemestre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSemestre.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabelSemestre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabelCodigo1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCodigo1.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabelCodigo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCodigo1.setText("Código");

        jLabelEdad1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdad1.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabelEdad1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelEdad1.setText("Edad");

        jLabelFinan1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFinan1.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabelFinan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFinan1.setText("Financiación");

        jLabelSemestre1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSemestre1.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabelSemestre1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSemestre1.setText("Semestre");

        jLabelNomPaciente1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNomPaciente1.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabelNomPaciente1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNomPaciente1.setText("Nombre del Paciente");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextFieldObservaciones.setColumns(20);
        jTextFieldObservaciones.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jTextFieldObservaciones.setRows(5);
        jScrollPane1.setViewportView(jTextFieldObservaciones);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelFinan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCodigo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelSemestre1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelNomPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelFinan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNomPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodigo1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFinan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelFinan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSemestre1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 590, 510));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 1300, 560));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 1300, 620));

        jLabel4.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel4.setText("Asesoría");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed

    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed

    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void rSButtonMetro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro3ActionPerformed

    }//GEN-LAST:event_rSButtonMetro3ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        irRegistrarPsicologoJPanel();
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        irAsesoriaJPanel();
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        irHistorialJPanel();
    }//GEN-LAST:event_boton3ActionPerformed

    private void guardarAsesoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAsesoriaActionPerformed
        try {
            if (!jTextFieldNumAsesoria.getText().isEmpty()
                    || !jTextFieldTipAcomp.getText().isEmpty()
                    || !jTextFieldAcceso.getText().isEmpty()
                    || !jTextFieldRemitidoPor.getText().isEmpty()
                    || !jTextFieldProblema.getText().isEmpty()
                    || !jTextFieldAcciones.getText().isEmpty()
                    || !jTextFieldAsistencia.getText().isEmpty()
                    || !jTextFieldCulminacion.getText().isEmpty()
                    || !jTextFieldRemitidoA.getText().isEmpty()
                    || !jTextFieldObservaciones.getText().isEmpty()) {
                int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro desea guardar la Asesoría?", "Confirmación de Asesoría", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (respuesta == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(null, asesoriaB.createAsesoria(Integer.parseInt(jTextFieldNumAsesoria.getText()),
                            ObtenerFecha(),
                            jTextFieldTipAcomp.getText(),
                            jTextFieldAcceso.getText(),
                            jTextFieldRemitidoPor.getText(),
                            jTextFieldProblema.getText(),
                            jTextFieldAcciones.getText(),
                            jTextFieldAsistencia.getText(),
                            jTextFieldCulminacion.getText(),
                            jTextFieldRemitidoA.getText(),
                            jTextFieldObservaciones.getText(),
                            buscarPaciente().getDocumento(),
                            inicio.darDocumentoUsuario()
                    ));
                    limpiar();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Algun campo esta vacio. Por favor llene todos los campos necesarios para registrar a un pasciente.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algun registro está mal escrito. Por favor compruebe todos los campos.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarAsesoriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (buscarPaciente() == null) {
            JOptionPane.showMessageDialog(this, "Error. No se encontro el pacinete.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            jLabelNomPaciente.setText(buscarPaciente().getNombres() + " " + buscarPaciente().getApellidos());
            jLabelCodigo.setText(buscarPaciente().getCodigo());
            jLabelEdad.setText(buscarPaciente().getEdad() + "");
            jLabelFinan.setText(buscarPaciente().getFinanciacion());
            jLabelSemestre.setText(buscarPaciente().getSemestre());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        irRegistrarJPanel();
    }//GEN-LAST:event_boton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        irIniciarSesionJPanel();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private co.edu.usbbog.paoe.view.image.Boton boton1;
    private co.edu.usbbog.paoe.view.image.Boton boton2;
    private co.edu.usbbog.paoe.view.image.Boton boton3;
    private co.edu.usbbog.paoe.view.image.Boton boton4;
    private javax.swing.JButton guardarAsesoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEdad1;
    private javax.swing.JLabel jLabelFinan;
    private javax.swing.JLabel jLabelFinan1;
    private javax.swing.JLabel jLabelNomPaciente;
    private javax.swing.JLabel jLabelNomPaciente1;
    private javax.swing.JLabel jLabelSemestre;
    private javax.swing.JLabel jLabelSemestre1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldAcceso;
    private javax.swing.JTextField jTextFieldAcciones;
    private javax.swing.JTextField jTextFieldAsistencia;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCulminacion;
    private javax.swing.JTextField jTextFieldNumAsesoria;
    private javax.swing.JTextArea jTextFieldObservaciones;
    private javax.swing.JTextField jTextFieldProblema;
    private javax.swing.JTextField jTextFieldRemitidoA;
    private javax.swing.JTextField jTextFieldRemitidoPor;
    private javax.swing.JTextField jTextFieldTipAcomp;
    private javax.swing.JLabel nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
