/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.paoe.view.panel;

import co.edu.usbbog.paoe.controller.logic.PsicologoBusiness;
import co.edu.usbbog.paoe.security.Seguridad;
import co.edu.usbbog.paoe.view.frame.Principal;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Nicolas
 */
public class RegistrarPsicologoJPanel extends javax.swing.JPanel {

    private Principal principal;
    private IniciarSesionJPanel inicio;
    private Seguridad seguridad;
    private PsicologoBusiness psicologoB;

    /**
     * Creates new form Presentacion
     */
    public RegistrarPsicologoJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
        this.inicio = new IniciarSesionJPanel(principal);
        this.nombreUsuario.setText(inicio.darNombreUsuario());
        this.psicologoB = new PsicologoBusiness();
        this.seguridad = new Seguridad();
    }

    private void irRegistrarJPanel() {
        principal.irRegistrarJPanel(this);
    }

    private void irAsesoriaJPanel() {
        principal.irAsesoriaJPanel(this);
    }

    private void irHistorialJPanel() {
        principal.irHistorialJPanel(this);
    }

    private void irIniciarSesionJPanel() {
        principal.irIniciarSesionJPanel(this);
    }

    private void irRegistrarPsicologoJPanel() {
        principal.irRegistrarPsicologoJPanel(this);
    }

    public void limpiar() {
        cedula.setText("");
        nombre.setText("");
        apellido.setText("");
        edad.setText("");
        correo.setText("");
        contrasena.setText("");
        contrasena1.setText("");
        telefono.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nombreUsuario = new javax.swing.JLabel();
        boton1 = new co.edu.usbbog.paoe.view.image.Boton();
        boton2 = new co.edu.usbbog.paoe.view.image.Boton();
        boton3 = new co.edu.usbbog.paoe.view.image.Boton();
        jButton3 = new javax.swing.JButton();
        boton4 = new co.edu.usbbog.paoe.view.image.Boton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contrasena = new javax.swing.JPasswordField();
        contrasena1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nunito", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APPAOE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/emociones.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/river.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 1580, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        nombreUsuario.setFont(new java.awt.Font("Nunito", 1, 15)); // NOI18N
        nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuario.setText("Psicólogo");

        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/nota.png"))); // NOI18N
        boton1.setText("Registrar Paciente");
        boton1.setColorHover(new java.awt.Color(204, 204, 204));
        boton1.setColorNormal(new java.awt.Color(214, 217, 223));
        boton1.setColorPressed(new java.awt.Color(153, 153, 153));
        boton1.setColorTextHover(new java.awt.Color(0, 0, 0));
        boton1.setColorTextNormal(new java.awt.Color(0, 0, 0));
        boton1.setColorTextPressed(new java.awt.Color(0, 0, 0));
        boton1.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/emocion.png"))); // NOI18N
        boton2.setText("Asesoría");
        boton2.setColorHover(new java.awt.Color(204, 204, 204));
        boton2.setColorNormal(new java.awt.Color(214, 217, 223));
        boton2.setColorPressed(new java.awt.Color(153, 153, 153));
        boton2.setColorTextHover(new java.awt.Color(0, 0, 0));
        boton2.setColorTextNormal(new java.awt.Color(0, 0, 0));
        boton2.setColorTextPressed(new java.awt.Color(0, 0, 0));
        boton2.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/dosier.png"))); // NOI18N
        boton3.setText("Historial");
        boton3.setColorHover(new java.awt.Color(204, 204, 204));
        boton3.setColorNormal(new java.awt.Color(214, 217, 223));
        boton3.setColorPressed(new java.awt.Color(153, 153, 153));
        boton3.setColorTextHover(new java.awt.Color(0, 0, 0));
        boton3.setColorTextNormal(new java.awt.Color(0, 0, 0));
        boton3.setColorTextPressed(new java.awt.Color(0, 0, 0));
        boton3.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/apagar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/psicologo.png"))); // NOI18N
        boton4.setText("Registrar Psicólogo");
        boton4.setColorHover(new java.awt.Color(204, 204, 204));
        boton4.setColorNormal(new java.awt.Color(214, 217, 223));
        boton4.setColorPressed(new java.awt.Color(153, 153, 153));
        boton4.setColorTextHover(new java.awt.Color(0, 0, 0));
        boton4.setColorTextNormal(new java.awt.Color(0, 0, 0));
        boton4.setColorTextPressed(new java.awt.Color(0, 0, 0));
        boton4.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(boton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
            .addComponent(boton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(boton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(nombreUsuario)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(160, 160, 160)
                .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 230, 740));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/anadir.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 40, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/paoe/view/image/salvar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 40, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabel8.setText("Cédula");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 76, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabel9.setText("Nombre");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 126, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabel10.setText("Apellido");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 176, -1, -1));

        cedula.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jPanel4.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 73, 237, -1));

        nombre.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jPanel4.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 123, 237, -1));

        apellido.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jPanel4.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 173, 237, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabel11.setText("Datos del Psicólogo");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 29, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabel12.setText("Edad");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 226, -1, -1));

        edad.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jPanel4.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 223, 237, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabel13.setText("Correo electrónico");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 276, -1, -1));

        correo.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jPanel4.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 273, 237, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabel14.setText("Contraseña");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 325, -1, -1));

        telefono.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jPanel4.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 415, 237, -1));

        jLabel5.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabel5.setText("Teléfono");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 418, -1, -1));

        contrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 323, 237, -1));

        contrasena1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(contrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 369, 237, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 590, 500));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 1300, 570));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 1300, 620));

        jLabel4.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel4.setText(" Registrar Psicólogo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed

    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed

    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void rSButtonMetro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro3ActionPerformed

    }//GEN-LAST:event_rSButtonMetro3ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        irRegistrarJPanel();
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        irAsesoriaJPanel();
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        irHistorialJPanel();
    }//GEN-LAST:event_boton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (cedula.getText().isEmpty()
                || nombre.getText().isEmpty()
                || apellido.getText().isEmpty()
                || edad.getText().isEmpty()
                || correo.getText().isEmpty()
                || contrasena.getText().isEmpty()
                || contrasena1.getText().isEmpty()
                || telefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Algun campo esta vacio. Por favor llene todos los campos.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (!contrasena.getText().equals(contrasena1.getText())) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no cooinciden. Por favor verifique de nuevo.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, psicologoB.createPsicologo(Integer.parseInt(cedula.getText()), nombre.getText(), apellido.getText(), Integer.parseInt(edad.getText()), correo.getText(), seguridad.encriptar("IngenierosSistemas", contrasena.getText()), telefono.getText()));
    
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        irRegistrarPsicologoJPanel();
    }//GEN-LAST:event_boton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        irIniciarSesionJPanel();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private co.edu.usbbog.paoe.view.image.Boton boton1;
    private co.edu.usbbog.paoe.view.image.Boton boton2;
    private co.edu.usbbog.paoe.view.image.Boton boton3;
    private co.edu.usbbog.paoe.view.image.Boton boton4;
    private javax.swing.JTextField cedula;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JPasswordField contrasena1;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField edad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
